<?php /** @var \Awesome\Base\Block\Html\Head $this */ ?>
<?php $mediaUrl = $this->getMediaUrl(); ?>
<?php $staticUrl = $this->getStaticUrl(); ?>
<meta charset="UTF-8">
<title><?= $this->getTitle(); ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="<?= $mediaUrl . $this->getFavicon(); ?>"/>
<?php foreach($this->getStyles() as $css): ?>
    <link rel="stylesheet" type="text/css" href="<?= $staticUrl . $css['src']; ?>"/>
<?php endforeach; ?>
<?php foreach($this->getScripts() as $script): ?>
    <script src="<?= $staticUrl . $script['src']; ?>"></script>
<?php endforeach; ?>
