<?php /** @var \Awesome\Base\Block\Template $this */ ?>
<div class="content">
    <div class="timer-container">
        <div class="timer-wrapper radial-container">
            <div class="timer-button-container">
                <button class="timer-button" type="button" name="start-stop" value="Start/Stop">
                    <span class="time-value no-select">15:30</span>
                    <span class="timer-button-title no-select" style="display: block; bottom: 0; position: absolute; left: 50%; transform: translateX(-50%)"></span>
                </button>
            </div>
            <div class="radial-percentage-value" style="display: none"></div>
            <div class="radial-slider">
                <div class="radial-controller"></div>
            </div>
            <div class="loader">
                <div class="vjs-loading-spinner"></div>
            </div>
        </div>
        <div class="random-button-container">
            <button class="random-button" type="button" name="random-button" value="Set random time">
                <span class="random-icon"></span>
                <span class="random-button-title">Random</span>
            </button>
        </div>
    </div>
</div>
<script>
//    @TODO: temporary hint functionality, should be updated and removed
    function showX() {
        jQuery('.menu').removeClass('active');
        jQuery('.hint').show();
    }

    function hideX() {
        jQuery('.hint').hide();
        localStorage.setItem('hint', 'true');
    }

    let shown = localStorage.getItem('hint');

    if (!shown) {
        showX();
    }
</script>
<script type="application/javascript">
    jQuery(function () {
    $('.random-time.range-slider').rangeSlider({
        difference: 1,
        minValue: 1,
        maxValue: 10
    });
    $('.settings').settings({
        hideRandomTime: 1,
        minDefaultValue: 1,
        maxDefaultValue: 5,
        showLoader: 1
    });
    $('.timer-container').timer({
        defaultTime: 2,
    });
    $('.timer-wrapper.radial-container').radialSlider({});
});
</script>
