<?php /** @var \Awesome\Timer\Block\Timer $block */ ?>
<div class="content">
    <div class="timer-container" data-awesome-init='{"timer": <?= $block->getTimerConfigJson() ?>}'>
        <div class="timer-wrapper radial-container" data-awesome-init='{"radialSlider": {}}'>
            <div class="timer-button-container">
                <button class="timer-button button-play" type="button" title="<?= __('Play') ?>" data-timer-control>
                    <svg class="button-play__icon" viewBox="0 0 40 40" stroke-linejoin="round">
                        <path class="button-play__triangle" d="M6 6 L20 13 L20 27 L6 34 z M20 13 L34 20 L34 20 L20 27 z">
                            <animate attributeName="d" to="M6 6 L14 6 L14 34 L6 34 z M26 6 L34 6 L34 34 L26 34 z"
                                     begin="" dur="0.3s" fill="freeze" data-pause-animation/>
                            <animate attributeName="d" to="M6 6 L20 13 L20 27 L6 34 z M20 13 L34 20 L34 20 L20 27 z"
                                     begin="" dur="0.3s" fill="freeze" data-play-animation/>
                        </path>
                        <script>
                            (new MutationObserver((event) => {
                                const contain = event[0].target.classList.contains('active');

                                if (event[0].oldValue.includes('active') !== contain) {
                                    event[0].target.querySelector(contain ? '[data-pause-animation]' : '[data-play-animation]').beginElement();
                                }
                            })).observe(document.currentScript.parentNode.parentNode, { attributeFilter: ['class'], attributeOldValue: true });
                        </script>
                    </svg>
                    <span class="timer-time" style="display: block; bottom: 0; position: absolute; left: 50%; transform: translateX(-50%)"></span>
                </button>
            </div>
            <div class="radial-slider">
                <div class="radial-controller"></div>
            </div>
            <div class="loader">
                <div class="vjs-loading-spinner"></div>
            </div>
        </div>
        <div class="random-button-container">
            <button class="random-button" type="button" name="random-button" value="Set random time">
                <span class="random-icon"></span>
                <span class="random-button-title">Random</span>
            </button>
        </div>
    </div>
    <?= $block->getChildHtml('timer.hint') ?>
</div>
