<?php /** @var \Awesome\Timer\Block\Timer $block */ ?>
<div class="content">
    <div class="timer-container" data-awesome-init='{"timer": <?= $block->getTimerConfigJson(); ?>}'>
        <div class="timer-wrapper radial-container" data-awesome-init='{"radialSlider": {}}'>
            <div class="timer-button-container">
                <button class="timer-button" type="button" name="start-stop" value="Start/Stop">
                    <span class="timer-time noselect" style="display: block; bottom: 0; position: absolute; left: 50%; transform: translateX(-50%)"></span>
                </button>
            </div>
            <div class="radial-slider">
                <div class="radial-controller"></div>
            </div>
            <div class="loader">
                <div class="vjs-loading-spinner"></div>
            </div>
        </div>
        <div class="random-button-container">
            <button class="random-button" type="button" name="random-button" value="Set random time">
                <span class="random-icon"></span>
                <span class="random-button-title">R</span>
            </button>
        </div>
    </div>
</div>
