<?php /** @var \Vch\Frontend\Block\Html\Head $block */ ?>
<head>
    <meta charset="UTF-8">
    <?= $block->getTitleHtml() ?>
    <?= $block->getDescriptionHtml() ?>
    <?= $block->getKeywordsHtml() ?>
    <?= $block->getRobotsHtml() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?= $block->getFaviconHtml() ?>
    <?= $block->getManifestHtml() ?>
    <?= $block->getPreloadsHtml() ?>
    <?= $block->getStylesHtml() ?>
    <?= $block->getScriptsHtml() ?>
    <?= $block->getHeadAdditional() ?>
</head>
