<?php /** @var \Awesome\Frontend\Block\Header $block */ ?>
<header>
    <?= $block->getChildHtml(''); ?>
    <div class="logo-container">
        <?php if (!$isHomepage = $block->isHomepage()): ?>
            <a href="/">
        <?php endif; ?>
                <img src="<?= $block->getLogo(); ?>" alt="AlcoTimer" class="no-select"/>
        <?php if (!$isHomepage): ?>
            </a>
        <?php endif; ?>
    </div>
</header>
