<?php /** @var \Awesome\Frontend\Block\Header $block */ ?>
<header>
    <?= $block->getChildHtml('') ?>
    <div class="logo__container">
        <?php if (!$isHomepage = $block->isHomepage()): ?>
            <a href="/">
        <?php endif; ?>
                <img class="logo__image" src="<?= $block->getLogo() ?>" alt="AlcoTimer Logo"/>
        <?php if (!$isHomepage): ?>
            </a>
        <?php endif; ?>
    </div>
</header>
