<?php /** @var \Awesome\Frontend\Block\Menu $block */ ?>
<?php $supportEmailAddress = $block->getSupportEmailAddress(); ?>
<div class="menu" data-awesome-init='{"menu": {}}'>
    <div class="menu-list">
        <div class="title">
            <h2><?= __('Menu'); ?></h2>
            <p style="text-align: right;font-size: 14px;"><?= \Awesome\Framework\Model\Http::VERSION; ?> open beta</p>
            <!-- @TODO: temporary public versing -->
        </div>
        <?= $block->getChildHtml('timer.settings'); ?>
        <div class="contact-us">
            <p><?= __('Face any bug or have interesting ideas?'); ?></p>
            <p><?= __('Send us an email:'); ?>
                <a href="mailto:<?= $supportEmailAddress; ?>?subject = AlcoTimer"
                   class="mail-address word-break" data-awesome-init='{"copy": {}}'><?= $supportEmailAddress; ?></a>
            </p>
        </div>
    </div>
</div>
