<?php /** @var \Awesome\Timer\Block\Timer $block */ ?>
<div class="settings" data-awesome-init='{"settings": <?= $block->getSettingsJson(); ?>}'>
    <ul>
        <li>
            <div class="random-time range-slider" data-awesome-init='{"rangeSlider": <?= $block->getSliderConfigJson(); ?>}'>
                <h3><?= __('Set time range (minutes):'); ?></h3>
                <div class="range-controls">
                    <div class="controller min"></div>
                    <div class="controller max"></div>
                </div>
                <div class="range-inputs">
                    <input type="number" class="value min" name="min-time-input" aria-label="<?= __('Minimum random time input value'); ?>">
                    <span class="input-separator">- to -</span>
                    <input type="number" class="value max" name="max-time-input" aria-label="<?= __('Maximum random time input value'); ?>">
                </div>
            </div>
        </li>
        <li>
            <div class="random-time checkbox">
                <input type="checkbox" class="hide-random-time" name="hide-random-time" id="hide-random-time">
                <label for="hide-random-time"><?= __('Hide random time'); ?></label>
            </div>
        </li>
        <li>
            <div class="loader-settings checkbox">
                <input type="checkbox" class="show-loader" name="show-loader" id="show-loader" checked>
                <label for="show-loader"><?= __('Show loader on run'); ?></label>
            </div>
        </li>
    </ul>
    <div class="settings-buttons-container">
        <button class="reset-button" type="button" name="settings-reset" value="Reset  settings"><?= __('Reset'); ?></button>
        <button class="apply-button" type="button" name="settings-apply" value="Apply Settings"><?= __('Apply'); ?></button>
    </div>
</div>
