<?php /** @var \Awesome\Timer\Block\Timer $block */ ?>
<div class="settings" data-awesome-init='{"settings": <?= $block->getSettingsJson(); ?>}'>
    <ul>
        <li>
            <div class="random-time range-slider" data-awesome-init='{"rangeSlider": {}}'>
                <h3>Set time range (mins):</h3>
                <div class="range-controls">
                    <div class="min-controller time"></div>
                    <div class="max-controller time"></div>
                </div>
                <div class="range-inputs">
                    <input type="number" class="min-value time" name="min-time-input" id="min-time-input">
                    <label for="min-time-input" style="display: none">Minimum random time input value</label>
                    <span class="input-separator">- to -</span>
                    <input type="number" class="max-value time" name="max-time-input" id="max-time-input">
                    <label for="max-time-input" style="display: none">Maximum random time input value</label>
                </div>
            </div>
        </li>
        <li>
            <div class="random-time checkbox">
                <input type="checkbox" class="hide-random-time" name="hide-random-time" id="hide-random-time">
                <label for="hide-random-time">Hide random time</label>
            </div>
        </li>
        <li>
            <div class="loader-settings checkbox">
                <input type="checkbox" class="show-loader" name="show-loader" id="show-loader" checked>
                <label for="show-loader">Show loader on run</label>
            </div>
        </li>
    </ul>
    <div class="settings-buttons-container">
        <button class="reset-button" type="button" name="settings-reset" value="Reset  settings">Reset</button>
        <button class="apply-button" type="button" name="settings-apply" value="Apply Settings">Apply</button>
    </div>
</div>
<div class="hint-button-container">
    <button type="button" class="hint-button">Show hint</button>
</div>
