<?php /** @var \Awesome\Frontend\Block\Template $block */ ?>
<div class="timer-hint">
    <div class="hint-content">
        <h2 class="hint-title">Hint for newcomers!</h2>
        <p>Rules are simple: when time is over, you have to drink.</p>
        <p>Big red button in the center will start or stop the timer. Circular slider will help you to set up the time. And "Random" button.. will give you a random time left.</p>
        <p>Time interval can be configured in the menu, check the left-top corner of the page.</p>
        <button type="button" class="hint-confirm-button">Got it!</button>
    </div>
</div>
<script type="application/javascript">
    require([
        'jquery',
        'popup',
    ], function ($) {
        'use strict'

        let $timerHint = $('.timer-hint'),
            shown = localStorage.getItem('timerHintShown');

        $timerHint.popup({
            delayOnPageLoad: 500,
            confirmButtonSelector: '.hint-confirm-button', // @TODO: this kind of buttons must be used for modal confirm widgets
            triggerSelector: '.hint-button-container .hint-button',
            openOnPageLoad: !shown,
        });

        if (!shown) {
            $timerHint.one('popup.close', function () {
                localStorage.setItem('timerHintShown', 'true');
            })
        }
    });
    // @TODO: unite all timer data into one record in localstorage
</script>
