<?php /** @var \Awesome\Timer\Block\Timer $this */ ?>
<script type="application/javascript">
    jQuery(function () {
        $('.random-time.range-slider').rangeSlider(<?= $this->getRandomRangeConfigJson(); ?>);
        $('.settings').settings(<?= $this->getSettingsJson(); ?>);
        $('.timer-container').timer(<?= $this->getDefaultTimeJson(); ?>);
        $('.timer-wrapper.radial-container').radialSlider({});
    });
</script>
