<?php /** @var \Awesome\Ui\Block\Menu $block */ ?>
<?php $supportEmailAddress = $block->getSupportEmailAddress(); ?>
<div class="menu">
    <div class="menu-list">
        <div class="title">
            <h2>AlcoMenu</h2>
            <p style="text-align: right;font-size: 14px;"><?= \Awesome\Framework\Model\AppInterface::VERSION; ?> open beta</p>
            <!-- @TODO: temporary public versing -->
        </div>
        <?= $block->getChildHtml('timer.settings'); ?>
        <div class="contact-us">
            <p>Face any bug or have new ideas?</p>
            <p>Send us an email:
                <a href="mailto:<?= $supportEmailAddress; ?>?subject = AlcoTimer" class="mail-address word-break copy-on-click">
                    <?= $supportEmailAddress; ?>
                </a>
            </p>
        </div>
    </div>
</div>
