<?php /** @var \Awesome\Frontend\Block\Template $block */ ?>
<div class="visualizer">
    <div class="legend">
        <span class="trackname">-</span>
        <span class="timecode">--:--:--</span>
    </div>
    <canvas class="canvas" height="900" width="900"></canvas>
    <audio class="player" controls="true" crossorigin="anonymous"></audio>
</div>
<script type="text/x-awesome-init">
{
    ".visualizer": {
        "player": {}
    }
}
</script>
