<?php /** @var \Awesome\Framework\Block\Html\Head $this */ ?>
<meta charset="UTF-8">
<title><?= $this->getTitle(); ?></title>
<meta name="description" content="<?= $this->getDescription(); ?>"/>
<meta name="keywords" content="<?= $this->getKeywords(); ?>"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link rel="shortcut icon" type="image/png" href="<?= $this->getMediaUrl($this->getFavicon()); ?>"/>
<?php foreach($this->getLibs() as $lib): ?>
    <script src="<?= $this->getStaticUrl($lib); ?>"></script>
<?php endforeach; ?>
<?php foreach($this->getStyles() as $css): ?>
    <link rel="stylesheet" type="text/css" href="<?= $this->getStaticUrl($css); ?>"/>
<?php endforeach; ?>
<?php foreach($this->getScripts() as $script): ?>
    <script src="<?= $this->getStaticUrl($script); ?>"></script>
<?php endforeach; ?>
