<?php /** @var \Vch\Timer\Block\Timer $block */ ?>
<div class="settings" data-awesome-init='{"settings": <?= $block->getSettingsJson(); ?>}'>
    <ul>
        <li>
            <div class="random-time range-slider" data-awesome-init='{"rangeSlider": <?= $block->getSliderConfigJson(); ?>}'>
                <h3><?= __('Set time range (minutes):'); ?></h3>
                <div class="range-controls">
                    <div class="controller min"></div>
                    <div class="controller max"></div>
                </div>
                <div class="range-inputs">
                    <input class="value min input" name="min-time-input" type="number" aria-label="<?= __('Minimum random time input value'); ?>">
                    <span class="input-separator">- to -</span>
                    <input class="value max input" name="max-time-input" type="number" aria-label="<?= __('Maximum random time input value'); ?>">
                </div>
            </div>
        </li>
        <li>
            <div class="random-time">
                <label class="label">
                    <input class="hide-random-time checkbox" name="hide-random-time" type="checkbox">
                    <?= __('Hide random time') ?>
                </label>
            </div>
        </li>
        <li>
            <div class="loader-settings">
                <label class="label">
                    <input class="show-loader checkbox" name="show-loader" type="checkbox" checked>
                    <?= __('Show loader on run') ?>
                </label>
            </div>
        </li>
    </ul>
    <div class="settings-buttons-container">
        <button class="reset-button button" type="button"><?= __('Reset') ?></button>
        <button class="apply-button button button--primary" type="button"><?= __('Apply') ?></button>
    </div>
</div>
