<?php /** @var \Awesome\Frontend\Block\Html\Head $block */ ?>
<meta charset="UTF-8">
<?php if ($title = $block->getTitle()): ?>
    <title><?= $title; ?></title>
<?php endif; ?>
<?php if ($description = $block->getDescription()): ?>
    <meta name="description" content="<?= $description; ?>"/>
<?php endif; ?>
<?php if ($keywords = $block->getKeywords()): ?>
    <meta name="keywords" content="<?= $keywords; ?>"/>
<?php endif; ?>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
<?php if ($favicon = $block->getFavicon()): ?>
    <link rel="shortcut icon" type="image/png" href="<?= $block->getMediaUrl($favicon); ?>"/>
<?php endif; ?>
<?php foreach($block->getLibs() as $lib): ?>
    <script src="<?= $lib; ?>"></script>
<?php endforeach; ?>
<?php foreach($block->getStyles() as $css): ?>
    <link rel="stylesheet" type="text/css" href="<?= $css; ?>"/>
<?php endforeach; ?>
<?php foreach($block->getScripts() as $script): ?>
    <script src="<?= $script; ?>"></script>
<?php endforeach; ?>
