<?php /** @var \Awesome\Frontend\Block\Html\Head $block */ ?>
<head>
    <meta charset="UTF-8">
    <?= $block->getTitleHtml(); ?>
    <?= $block->getDescriptionHtml(); ?>
    <?= $block->getKeywordsHtml(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?= $block->getFaviconHtml(); ?>
    <?= $block->getPreloadsHtml(); ?>
    <?= $block->getStylesHtml(); ?>
    <?= $block->getScriptsHtml(); ?>
    <?= $block->getHeadAdditional(); ?>
</head>
